package common;

public enum TypKomunikatu {
    LOGIN,
    REJESTRACJA,
    DODAJ_UZYTKOWNIKA,
    POBIERZ_UZYTKOWNIKOW,
    USUN_UZYTKOWNIKA,
    EDYTUJ_UZYTKOWNIKA,
    POBIERZ_SZABLONY,
    DODAJ_SZABLON,
    EDYTUJ_SZABLON,
    USUN_SZABLON,
    ODPOWIEDZ_OK,
    ODPOWIEDZ_BLAD
}
