package common;

public enum TypKomunikatu {
    LOGIN,
    REJESTRACJA,
    DODAJ_UZYTKOWNIKA,
    POBIERZ_UZYTKOWNIKOW,
    USUN_UZYTKOWNIKA,
    EDYTUJ_UZYTKOWNIKA,
    POBIERZ_SZABLONY,
    POBIERZ_SZABLON,
    DODAJ_SZABLON,
    EDYTUJ_SZABLON,
    USUN_SZABLON,
    ZAPISZ_ANKIETE,
    SPRAWDZ_STATUS_ANKIETY,
    POBIERZ_MOJE_ANKIETY,
    ODPOWIEDZ_OK,
    ODPOWIEDZ_BLAD
}
